### ISSUE TITLE
int too long to convert

### ISSUE THREAD

**Issue by Pincode78** [abdulkadir-gungor/gngr_local_keylogger_for_windows#1]
i always get this error with the keylogger 
keyboard_log.py", line 57, in keyboard_listen
    hook_id = windll.user32.SetWindowsHookExA(win32con.WH_KEYBOARD_LL, pointer,
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert

but the screen log works great

can you help

**Comment by abdulkadir-gungor** [comment]
Hi, 
screen_log.py, keyboard_log.py and keylogger.py work great.

I wrote the Python codes on the x64 machine.  Your machine is getting an error because it's x32. 
You need to change the codes in line 45 and 65 below as follows.

**for x64 ;
(45. )            from ctypes import windll, CFUNCTYPE, POINTER, c_int, c_void_p, byref
(65. )            CMPFUNC = CFUNCTYPE(c_int, c_int, c_int, POINTER(c_void_p))**

**for x32;
(45. )             from ctypes import windll, CFUNCTYPE, POINTER, c_long, c_void_p, byref
(65. )             CMPFUNC = CFUNCTYPE(c_long, c_long, c_long, POINTER(c_void_p))**


I don't have a x32 machine right now. But the codes above will most likely solve your problem.

For more detailed information, you can check the following address: "https://docs.python.org/3/library/ctypes.html"
![a1](https://user-images.githubusercontent.com/71177413/115457131-babad800-a22c-11eb-83e0-8e58a6ee046b.JPG)


Also, I typed these codes according to the Turkish Q keyboard. You may need to make changes according to the keyboard type used in the "**keyboard_even**" function starting on line 103 and ending in line 362. I suggest you look at "https://docs.microsoft.com/tr-tr/dotnet/api/system.windows.forms.keys?view=net-5.0".

**Comment by abdulkadir-gungor** [comment]
I wrote the Python codes on the x64 machine. Your machine is getting an error because it's x32. You need to change the lines below as shown.

keyboard_log.py
--------------------

**for x64 ;
(45. )            from ctypes import windll, CFUNCTYPE, POINTER, c_int, c_void_p, byref
(65. )            CMPFUNC = CFUNCTYPE(c_int, c_int, c_int, POINTER(c_void_p))**

**for x32;
(45. )             from ctypes import windll, CFUNCTYPE, POINTER, c_long, c_void_p, byref
(65. )             CMPFUNC = CFUNCTYPE(c_long, c_long, c_long, POINTER(c_void_p))**


keylogger.py
----------------

**for x64 ;
(61. )            from ctypes import windll, CFUNCTYPE, POINTER, c_int, c_void_p, byref
(81. )            CMPFUNC = CFUNCTYPE(c_int, c_int, c_int, POINTER(c_void_p))**

**for x32;
(61. )             from ctypes import windll, CFUNCTYPE, POINTER, c_long, c_void_p, byref
(81. )             CMPFUNC = CFUNCTYPE(c_long, c_long, c_long, POINTER(c_void_p))**

I don't have a x32 machine right now. However, the feedback I received told me that the above changes fixed the issue.

**The codes above will solve your problem.**
